version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html  
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    env_file:
      - .env
      
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: $USER_HOME/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: $USER_HOME/data/wordpress
      o: bind

networks:
  network:
    driver: bridge