version: "3"
services:
  ngnix:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    restart: always
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    ports: 
      - "8082:80"
    restart: always
    networks:
      - network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    depends_on:
    ports: 
      - "8082:80"
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge